# hugo.toml

baseURL = "https://gem-cp.github.io/hugo-api-poc/"
languageCode = "de-de"
title = "API PoC and Integrated Docs"

# Docsy Theme und Hugo Version
# Das theme-Schlüsselwort ist optional, wenn du das Theme als Modul lädst.
# theme = "github.com/google/docsy"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
  
  # --- Multirepo Configuration ---

  # Import von spec-VSDM2
  [[module.imports]]
    path = "github.com/gematik/spec-vsdm2"
    [[module.imports.mounts]]
      source = "docs"
      target = "content/docs/vsdm2"
    [[module.imports.mounts]]
      source = "images"
      target = "static/docs/vsdm2/images"
    # WIR STELLEN DEN URSPRÜNGLICHEN MOUNT WIEDER HER
    [[module.imports.mounts]]
      source = "README.md"
      target = "content/docs/vsdm2/_index.md" 

  # Import von zeta
  [[module.imports]]
    path = "github.com/gematik/zeta"
    [[module.imports.mounts]]
      source = "docs"
      target = "content/docs/zeta"
    [[module.imports.mounts]]
      source = "images"
      target = "static/docs/zeta/images"
    # WIR STELLEN DEN URSPRÜNGLICHEN MOUNT WIEDER HER
    [[module.imports.mounts]]
      source = "index.md"
      target = "content/docs/zeta/_index.md"

# Markdown Konfiguration
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    style = "monokai"
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2

# --- Hauptmenü für die obere Navigationsleiste ---

[[menu.main]]
  name = "TI 2.0 API Dokumentation"
  weight = 10
  identifier = "docs"
  # pageRef verweist auf die Inhaltsdatei. Hugo generiert die korrekte URL.
  pageRef = "/docs"

# Ein einziger Block, der alles regelt.
[[cascade]]
  [cascade._target]
    # Gilt für alle Inhalte unter /docs
    path = "/docs/**"
  [cascade.page]
    # Weist allen Seiten das korrekte Docsy-Layout zu
    type = "docs"